### ISSUE TITLE
Missing URL prompt in OPTION 2: Decoders (PP, URL) > OPTION 1: ProofPoint Decoder

### ISSUE THREAD

**Issue by noconnor29** [TheresAFewConors/Sooty#1]
OPTION 2: Decoders (PP, URL) > OPTION 1: ProofPoint Decoder

This option works (the URL is decoded correctly) but upon selecting 'OPTION 1' you're taken to the next line with no prompt for the URL. 

Using 'OPTION 2: URL Decoder' presents you with 'url: ' which I think is the intended behavior.

**Comment by noconnor29** [comment]
> OPTION 2: Decoders (PP, URL) > OPTION 1: ProofPoint Decoder
> 
> This option works (the URL is decoded correctly) but upon selecting 'OPTION 1' you're taken to the next line with no prompt for the URL.
> 
> Using 'OPTION 2: URL Decoder' presents you with 'url: ' which I think is the intended behavior.

It seems to work just by making edits to line 85:
`85             rewrittenurl = input('url: ')`

**Comment by TheresAFewConors** [comment]
It actually still works but there was no prompt to let you know that you could enter a proofpoint link - I've fixed it now so you should get a prompt that says 'Enter ProofPoint URL: ' - let me know if there's any further issues with it.

**Comment by noconnor29** [comment]
> It actually still works but there was no prompt to let you know that you could enter a Proofpoint link - I've fixed it now so you should get a prompt that says 'Enter ProofPoint URL: ' - let me know if there's any further issues with it.
> 
> Thanks for pointing that out, I missed it on the initial pass.

It definitely did work, sorry if I suggested otherwise. It's a small UX thing and was the only issue I noticed. Great tool, thanks for making it.

**Comment by TheresAFewConors** [comment]
All good buddy - thanks for pointing it out! 

Let me know if you spot any other issues
