### ISSUE TITLE
unable to run sooty.py

### ISSUE THREAD

**Issue by jsankr** [TheresAFewConors/Sooty#11]
When try to run Sooty.py in Kali after installing all requirement.txt using pip command with Python3 available.

Getting error when I ran python Sooty.py
Traceback (most recent call last):
  File "Sooty.py", line 13, in <module>
    import urllib.parse
ImportError: No module named parse

**Comment by TheresAFewConors** [comment]
can you try running `python3 install -r requirements.txt` and then running Sooty again? That specific error is tied to Python2 from what I can see. Let me know how that goes

**Comment by TheresAFewConors** [comment]
That specific error is tied to using Python 2.

https://stackoverflow.com/questions/29358403/no-module-named-urllib-parse-how-should-i-install-it
https://stackoverflow.com/questions/39648718/how-fix-no-module-named-parse-in-python3-4

Double check your python version with `python -v`
