### ISSUE TITLE
Link Unshortener - https://unshorten.it/

### ISSUE THREAD

**Issue by Arkanyus** [TheresAFewConors/Sooty#15]
Another good tool, may overlap with current options but worth mentioning since its had a few additions. The API is mentioned on the contact page.

**Comment by TheresAFewConors** [comment]
Not a bad suggestion, I'll take a look in the morning as it could be a nice addition to the decoder

**Comment by TheresAFewConors** [comment]
A URL unshortener has been added to the decoder block
