### ISSUE TITLE
More features:

### ISSUE THREAD

**Issue by andthenenteredalex** [TheresAFewConors/Sooty#21]
These are some more things I'm currently working on
VirusTotal
    -URL scan
    -submit file hash
Alien Vault OTX - pull reputation data on:
    -domain
    -ip
Apility (they have a free API, it has a rate limit, but I haven't hit it ever.
    -domain
    -ip

The more sources, the better, since some miss things. If there are more sources, a sort of average "combined threat score" can be found. Let me know if you're interested in any of these.

A few more I might be wanting to work on in the future are:
urlhaus - to pull urls and hashes
threatminer

**Comment by TheresAFewConors** [comment]
Sooty can already submit URL's and hashes to VirusTotal for reports,

The other features could be useful though. Take a look at how the VT reports are done in the rep checker and abuseIPDB do a similar system

**Comment by TheresAFewConors** [comment]
Creating comment to track features from this ticket. Corresponding card in Projects will be created for remaining features.

## VirusTotal
- ~~URL scan~~
- ~~submit file hash~~


## Alien Vault OTX - pull reputation data on:
- domain
- ip


## Apility 
(they have a free API, it has a rate limit, but I haven't hit it ever.
- domain
- ip

**Comment by TheresAFewConors** [comment]
Giving this a bump to see if it is still active.
