### ISSUE TITLE
HaveIBeenPwned API Now Authenticated and Priced

### ISSUE THREAD

**Issue by Arkanyus** [TheresAFewConors/Sooty#22]
Sadly, instead of just tying the API requests to tokens issued on an account like everyone else is doing, Troy has added a monthly cost to it's use. (Which paired with the recent announcement to sell HIBP hints towards a total cash-in on his end)

I suppose the necessary change here would be adding the token field like you've done with the others.

**Comment by TheresAFewConors** [comment]
Hi Arkanyus,

Thanks for updating me on this - I will take a look at it this week.

Thanks!

**Comment by TheresAFewConors** [comment]
So I just read the blog on why the pricing has been introduced and can understand where Troy is coming from. Unfortunately that means that the API will no longer be free, and will be removed on Aug 18th. So I will keep the functionality in Sooty until then, and remove it once it starts returning a 400 status. 

Closing this ticket as HIBP is unlikely to change their mind before then.
