### ISSUE TITLE
Pywin32 dependency install fails 

### ISSUE THREAD

**Issue by Beverdam** [TheresAFewConors/Sooty#25]
Pip install -r requirements.txt results in:

Collecting pywin32==224 (from -r requirements.txt (line 12))
  ERROR: Could not find a version that satisfies the requirement pywin32==224 (from -r requirements.txt (line 12)) (from versions: none)

Same for pip3. 

Tried this on both plain Ubuntu 18.04 LTS and Ubuntu 18.04 LTS in Windows subsystem for Linux: same error.

**Comment by TheresAFewConors** [comment]
Hi Beverdam,

Currently PyWin32 runs exclusively on Windows, so unfortunately the email/phishing module won't run on Ubuntu. I haven't found an appropriate alternative yet, however it is part of the next update to get full Linux compatibility for that specific block as well, including other extensions other than just .msg. 

It is high on the ToDo list, and ill update this thread once it's functioning correctly to let you know either way.
