### ISSUE TITLE
Reputation Checker can't handle domains

### ISSUE THREAD

**Issue by OpalSec** [TheresAFewConors/Sooty#26]
Using Office365.com as an example, the WhoIs and VT check work fine, but the next two don't:

```
 Checking BadIP's... 
  Error reaching BadIPs

 ABUSEIPDB Report:
   Error Reaching ABUSE IPDB
```

Whereas when using the IP that was resolved through the WhoIS check (52.165.129.203):
```
 Checking BadIP's... 
  IP not found

 ABUSEIPDB Report:
   IP:          52.165.129.203
   Reports:     0
   Abuse Score: 0%
   Last Report: None
```

Can the script not be tweaked to just use the IP resolved through the WhoIS check to perform those final two checks?

**Comment by TheresAFewConors** [comment]
Hi OpalSec,

That makes sense, I can tweak it to use the resolved address in case the domain fails. I'll keep this ticket open for now and update you when its been updated. 

Thanks for giving feedback

**Comment by TheresAFewConors** [comment]
Issue is now resolved. Modified the reputation checker to resolve domain names first and then use the resolved address by default. 

Closing.
