### ISSUE TITLE
Requirements.txt install fails on non-windows platforms

### ISSUE THREAD

**Issue by ekelson-bcove** [TheresAFewConors/Sooty#28]
requirements.txt file specifies pywin32 as a requirement, however this only applies if you are using windows.  It will fail if you are not.  Changing to `pywin32==224;  sys_platform == ‘windows’` will fix issue.

**Comment by TheresAFewConors** [comment]
Issue relates to #29 'Fixed Requirements File'.

**Comment by TheresAFewConors** [comment]
PR approved and merged with main branch. 

Good fix, adding to contributors section

**Comment by TheresAFewConors** [comment]
Added to contributors. Closing issue.
