### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Arkanyus** [TheresAFewConors/Sooty#3]
The following Error:

ubuntu@ubuntu-VirtualBox:~/Desktop$ python Sooty.py 
  File "Sooty.py", line 7
    [<]!DOCTYPE html[>]
    ^
SyntaxError: invalid syntax

**Comment by TheresAFewConors** [comment]
Just uploaded a new version that has some bug fixes, give that a try and let me know if the error continues

**Comment by TheresAFewConors** [comment]
That issue is caused by incorrectly downloading the script, if you are using `wget` or `curl`, you need to pull the `raw` version of the script, found [here](https://raw.githubusercontent.com/TheresAFewConors/Sooty/master/Sooty.py), otherwise you end up with the headers as well from the webpage.
