### ISSUE TITLE
WhoIs lookup endless loop

### ISSUE THREAD

**Issue by aki2419** [TheresAFewConors/Sooty#41]
**Describe the bug**
When using the Option 4: DNS lookup and select option 3: WHOIS Lookup, when entering any of the requested i.e. IP / Domain the result goes into endless loop, it does not exit after giving the output. See attached
<img width="185" alt="WhoIs-1" src="https://user-images.githubusercontent.com/34571464/70404186-42041300-1a5f-11ea-8526-57b65d288391.PNG">

**Reproduction Steps**
1. Select Option 4: DNS Lookup
2. Select option 3: WhoIs lookup
3. Enter any value and check
...

**Expected behavior**
It should have thrown the output and given another prompt to select options, rather it goes into endless loop.

**Screenshots**
attached screenshot

**Desktop Operating System:**
 - OS: [e.g. Win10, Linux, etc.]

**Additional context**

**Comment by aki2419** [comment]
@TheresAFewConors The same issue happens when we use Reputation Scanner

**Comment by naveci** [comment]
@aki2419 couple of questions as I cannot replicate it.

- what's your python version?
```
C:\Users\USER>python --version
Python 3.7.4
```
- Did you install in a virtual env of some sorts? Something like the following:
```
python -m venv venv
```
OR do you have a .venv or venv or something like that in the Sooty directory?

- Whats your pip list output? Should look something like this:

```
(venv) C:\Users\USER\Sooty>pip list
Package           Version
----------------- ---------
appdirs           1.4.3
asn1crypto        0.24.0
astroid           2.3.3
attrs             19.3.0
black             19.10b0
certifi           2019.6.16
cffi              1.12.3
chardet           3.0.4
Click             7.0
colorama          0.4.1
cryptography      2.7
dnspython         1.16.0
idna              2.8
ipwhois           1.1.0
isort             4.3.21
lazy-object-proxy 1.4.3
mccabe            0.6.1
pathspec          0.6.0
pip               19.3.1
pycparser         2.19
pylint            2.4.4
pyOpenSSL         19.0.0
PySocks           1.7.0
python-dateutil   2.8.1
pywin32           224
regex             2019.11.1
requests          2.22.0
ruamel.yaml       0.16.5
ruamel.yaml.clib  0.2.0
setuptools        40.8.0
six               1.12.0
strictyaml        1.0.6
toml              0.10.0
typed-ast         1.4.0
urllib3           1.24.2
wget              3.2
win-inet-pton     1.1.0
wincertstore      0.2
wrapt             1.11.2
```

**Comment by TheresAFewConors** [comment]
I tried it with the same `8.8.8.8` value seen in your screenshot and got a different output, seems to be working correctly here:

![image](https://user-images.githubusercontent.com/31410218/70445137-f66b5c80-1a92-11ea-9734-86d977fca31e.png)

Are you able to correctly ping the IP?

The issue you're having seems to be that the IP is not found, so it then attempts to resolve the address as a backup, and if  and looping again however that is causing the loop as it can't reach the IP given.

**Comment by aki2419** [comment]
@TheresAFewConors Thank you.. that makes sense now... Since ping is blocked at my workplace i can see that it must be looping to reach the destination.. Just a suggestion, for such scenarios can you change the code such that it will try 3 times and then exit out of the loop...

**Comment by TheresAFewConors** [comment]
@aki2419 Applied a fix that prevents the loop from occurring in the WhoIs lookup. The issue with the reputation check was originating from the WhoIs bug also. Both are now fixed.
