### ISSUE TITLE
Update to use Email Rep API Key

### ISSUE THREAD

**Issue by TheresAFewConors** [TheresAFewConors/Sooty#42]
**What is the feature that you are requesting?**
Update email rep checker to utilize API key for extended requests

**Additional information**
No

**Is your feature request related to a problem? Please describe.**
Currently limited with very few requests that can be used, using an API key gives two options depending on the key:
- Free: 50 queries per day
- Enterprise: Unlimited

Still allows for Sooty to make requests without a key, just provides further functionality.

**Comment by sarthak9426** [comment]
@TheresAFewConors can I take this issue?

**Comment by TheresAFewConors** [comment]
@sarthak9426 of course - I'll assign this to you now.

Thanks very much.

**Comment by TheresAFewConors** [comment]
linked PR and closed issue as resolved
