### ISSUE TITLE
StrictYaml Issue

### ISSUE THREAD

**Issue by cruisiejay** [TheresAFewConors/Sooty#47]
This is not a bug, I think this is just me being a rusher, but I am trying to debug my own issue trying to install this, 

I have run the requirments.txt against pip and install all the features, I am now in the process of running the sooty.py file

```
Traceback (most recent call last):
  File "Sooty.py", line 17, in <module>
    import strictyaml
ModuleNotFoundError: No module named 'strictyaml
```

But when checking

```
root@kali:/home/kali/Desktop# pip install strictyaml
Requirement already satisfied: strictyaml in /usr/local/lib/python2.7/dist-packages (1.0.6)
Requirement already satisfied: python-dateutil>=2.6.0 in /usr/local/lib/python2.7/dist-packages (from strictyaml) (2.8.1)
Requirement already satisfied: ruamel.yaml>=0.14.2 in /usr/local/lib/python2.7/dist-packages (from strictyaml) (0.16.7)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil>=2.6.0->strictyaml) (1.12.0)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" in /usr/local/lib/python2.7/dist-packages (from ruamel.yaml>=0.14.2->strictyaml) (0.2.0)
Requirement already satisfied: ruamel.ordereddict; platform_python_implementation == "CPython" and python_version <= "2.7" in /usr/local/lib/python2.7/dist-packages (from ruamel.yaml>=0.14.2->strictyaml) (0.4.14)
```

Looks like I already have it installed?

I wonder if you know how I could look at resolving this!  in the mean time

Kind Regards,

Jay,

**Comment by TheresAFewConors** [comment]
Hi @cruisiejay, it looks like the issue could be the Python version.

The logs shows that the strictyaml package is in your `/usr/local/lib/python2.7/dist-packages` folder, ie. Python 2.7. Sooty requires Python 3.3 or higher for a lot of the features, so this may be the cause. 

Would you be able to try it with Python 3 and see if the error still exists?

**Comment by naveci** [comment]
Please check your installed python version indeed.
`python --version`
if that spits out 2.7.x as @TheresAFewConors states, try the following:
`python3 --version`

Otherwise you might need to check if you even have python 3 installed on your system. A lot of the more "stable" linux distros still come with python 2.7 and so does MacOS. You need to manually install python 3.
With mac, this is easily done and managed through [homebrew](https://brew.sh)

**Comment by TheresAFewConors** [comment]
Looks like Kali is being used, so Py2.7 is the default afaik.

**Comment by cruisiejay** [comment]
Happy monday guys,  Thank you for the pointers so far

Version Check
``root@kali:/home/kali/Desktop# python --version
Python 2.7.17
root@kali:/home/kali/Desktop# python3 --version
Python 3.7.6``

Using python3

``root@kali:/home/kali/Desktop/Sooty# python3 Sooty.py 
Traceback (most recent call last):
  File "Sooty.py", line 17, in <module>
    import strictyaml"``

uninstalling and reinstalling the strictyaml module lead to no avail

**Comment by naveci** [comment]
Could you run a `pip3 list` in the same directory.
Also, I'm curious if you've installed virtual environment beforehand or just ran the `pip install -r requirements.txt` directly.

**Comment by cruisiejay** [comment]
@naveci I feel like such a layer 8 right now, nailed it using the wrong pip, completely forgot pip3 existed............

l
