### ISSUE TITLE
haveibeenpwned functionality 

### ISSUE THREAD

**Issue by Arkanyus** [TheresAFewConors/Sooty#5]
Would using the HIBP API similarly to the VT API be a possible feature request?

**Comment by TheresAFewConors** [comment]
That's a great suggestion. I'm working on a new module entirely for emails and I think your idea would be a good addition. I'll make sure it ends up in the email module (early next week most likely).

Thanks for the suggestion.

**Comment by TheresAFewConors** [comment]
Took a look and it was quite easy to add, so have an early version of a HIBP checker added to the project now. 

I'll close this case since the requested feature is not added. Thanks for the request.

**Comment by Arkanyus** [comment]
Fantastic, thank you. Appreciate your work.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TheresAFewConors** [comment]
No prob, if you think of any other features you want added feel free to request them - hope the tool is of some use to you
