### ISSUE TITLE
No Module named 'strictyaml'

### ISSUE THREAD

**Issue by oussama101** [TheresAFewConors/Sooty#50]
**Describe the bug**
Hi while I was trying to launch Sooty for the first time. I received a message error that no module named 'strictyaml'. This stopped launching Sooty
**Reproduction Steps**
1.navigate the the main branch on cli
2. launch Sooty by command python3 Sooty.py
3. error pop up and no further action
...

**Expected behavior**
Application to launch

**Screenshots**
![image](https://user-images.githubusercontent.com/42209877/75364566-eee57380-5889-11ea-9e8e-77305b88eaf7.png)

**Desktop Operating System:**
 - Kali Linux 2019.1

**Additional context**

**Comment by TheresAFewConors** [comment]
Hi @oussama101, thanks for opening an issue.

Have you installed from the requirements file first before launching Sooty for the first time?

**Comment by oussama101** [comment]
@TheresAFewConors  Yes. I have double-checked and all are marked as requirement already satisfied.

**Comment by TheresAFewConors** [comment]
could you try run `pip3 list` and see if the strictlyaml module exists there? It may be an issue using the wrong pip version.

**Comment by oussama101** [comment]
@TheresAFewConors  run the `pip3 list` and strictyaml module does not exist there.

**Comment by TheresAFewConors** [comment]
@oussama101 okay - looks like the issue is that its installing the modules for the wrong environment. could you try running: `pip3 install -r requirements.txt` and then verify the module installed with `pip3 list`?

**Comment by oussama101** [comment]
@TheresAFewConors  sorry for the delayed response. That seems to fix the issue. I was able to start Sooty after. Thank you for all the help much appreciated.

**Comment by TheresAFewConors** [comment]
@oussama101 Not prob, glad it worked for you.
