### ISSUE TITLE
Unable to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by Blason** [TheresAFewConors/Sooty#57]
Hi,

While installing we are getting below error

 **python3 Sooty.py**
Traceback (most recent call last):
  File "Sooty.py", line 11, in <module>
    import html.parser
ModuleNotFoundError: No module named 'html.parser'

**Comment by TheresAFewConors** [comment]
There seems to be several issues with Ubuntu 18.04.

Can you make sure you are using pip3 to install the requirements here? This has solved several similar issues in the past with downloading other packages.

**Comment by rajarshiparmar1410** [comment]
Use "pip3 install -r requirements.txt".

**Comment by TheresAFewConors** [comment]
closing due to lack of response
