### ISSUE TITLE
Add OPSEC leak disclaimer when using active features

### ISSUE THREAD

**Issue by Maijin** [TheresAFewConors/Sooty#59]
**What is the feature that you are requesting?**
Some features used in the tool can leak information to attackers and open source intelligence such as the scan to URLscan.
Therefore the tool should provide a one-shot disclaimer and a disclaimer likely in the README.

I would also suggest adding the passive alternative of scan -> search.

**Additional information**

Scanning on URLscan can lead to expose sensitive documents, sessions. It can also tip attacker that a specific campaign and even a specific email address is valid, information that they can use in a more advanced campaign.

![Example 1](https://user-images.githubusercontent.com/1408600/96969016-1e7c7680-1512-11eb-9e24-c902838b8b8b.png)
![Example 2 via j_opdenakker](https://user-images.githubusercontent.com/1408600/96969061-2a683880-1512-11eb-9dc9-04b5faca459e.png)

**Comment by TheresAFewConors** [comment]
Hi Maijin,

There's an open PR that sets the URLScan option to private instead to address this issue. The other options currently do not push by default to the various tools. 

I've assigned the PR to this issue.

Thanks for raising it.

**Comment by Maijin** [comment]
Yep, don't forget that private or public scan more than the URLScan.io public listing, both will also reach-out to attacker infrastructure therefore tipping the attacker about their on-going campaign/valid email address etc.

**Comment by jenetiks** [comment]
I can take a look at adding this in over the weekend! What would you think of providing the URLscan privacy policy instead? Something like:

"May want to check this out before submitting: <link>"
