### ISSUE TITLE
Sooty.py hard crashes Python3 on macOS 10.15.7

### ISSUE THREAD

**Issue by znb** [TheresAFewConors/Sooty#60]
**What is the Issue you are experiencing?**
All of the dependancies install without any issues. However when I run python3 Sooty.py Python crashes

**What Operating System are you using?**
macOS 10.15.7
Python 3.8.6

**Additional Information**
The issue appears to be in the libcrypto module

```
/usr/lib/libcrypto.dylib
abort() called
Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.
```

**Comment by mrn42** [comment]
See PR #63 to fix your issue
