### ISSUE TITLE
Change URLScan.io default -- add option?

### ISSUE THREAD

**Issue by jenetiks** [TheresAFewConors/Sooty#62]
**What is the feature that you are requesting?**
Default URLScan type to private

**Additional information**
Instead of defaulting to public, what do you think of defaulting to private with an option to choose what you want, or just hit enter to leave default?

**Is your feature request related to a problem? Please describe.**
No problem, just thinking. Before I submit a PR with changes, I wanted to bounce the idea off of you first since it is your baby after all.

**Additional context**
None. Just a privacy goof.

**Comment by TheresAFewConors** [comment]
that is total fine with me - its a good addition to switch to private by default in my opinion also. 

If you want to open a PR ill assign this issue to it as well. 

Thanks.
