### ISSUE TITLE
ModuleNotFoundError when trying to run

### ISSUE THREAD

**Issue by robmitch5** [TheresAFewConors/Sooty#73]
/Sooty-master/Sooty.py", line 10, in <module>
from unfurl import core   ModuleNotFoundError: No module named 'unfurl'
MacOS Catalina

**Comment by VAN1LLAG0RILLA** [comment]
Sounds like you'll need to manually add some modules. I was in the same boat

**Comment by TheresAFewConors** [comment]
ah Ill fix this now - one moment.

**Comment by TheresAFewConors** [comment]
ok that should be fixed now - the unfurl package was missing the version number so wasn't installing correctly. 

@robmitch5 can you redownload the requirements.txt file and try installing again?

**Comment by robmitch5** [comment]
redownloaded and unfortunately i receive the same error.

**Comment by TheresAFewConors** [comment]
did you reinstall from the requirements file? `pip install -r requirements.txt`

**Comment by robmitch5** [comment]
Same error " from unfurl import core
ImportError: No module named unfurl" ... reinstalled and requirements file 
  ***** $ pip install -r requirements.txt
Only one ignored : Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
All others Requirement already satisfied

**Comment by TheresAFewConors** [comment]
im unable to recreate this issue on my end - can you run `pip list` and see if there's a `dfir-unfurl` on there? should be listed as version: 20200812

**Comment by TheresAFewConors** [comment]
giving this a bump to see if the issue still persists - ill close out if no response.

**Comment by robmitch5** [comment]
thanks for the follow-up... I haven't had a look due to the holiday rush but I plan on checking within the next couple of days. 

will follow-up!

**Comment by TheresAFewConors** [comment]
Not to worry - ill keep this open for now then, enjoy the holiday break!

**Comment by robmitch5** [comment]
I've attempted a complete uninstall and reinstall. However, when I run python3 Sooty.py.  I get Traceback (most recent call last):
File "Sooty.py", line 11, in <module> from unfurl import core  ModuleNotFoundError: No module named 'unfurl'

When I run pip list I get the below.  
ansible            2.9.14
appdirs            1.4.4
asn1crypto         0.24.0
attrs              20.3.0
Babel              2.9.0
certifi            2019.6.16
cffi               1.12.3
chardet            3.0.4
click              7.1.2
click-log          0.3.2
cliff              3.5.0
cmd2               1.4.0
colorama           0.4.4
cryptography       2.7
decorator          4.4.2
**dfir-unfurl        20200812**
distlib            0.3.1
dnspython          1.16.0
filelock           3.0.12
Flask              1.1.2
Flask-Cors         3.0.9
flatbencode        0.2.1
future             0.18.2
gitdb              4.0.5
GitPython          3.1.11
idna               2.8
importlib-metadata 2.0.0
ipwhois            1.1.0
itsdangerous       1.1.0
Jinja2             2.11.2
jsonpointer        2.0
jsonschema         3.2.0
maclookup          1.0.3
MarkupSafe         1.1.1
networkx           2.5
pbr                5.5.1
pip                20.2.4
pipenv             2020.11.4
prettytable        0.7.2
protobuf           3.13.0
publicsuffix2      2.20191221
pycountry          20.7.3
pycparser          2.19
pyOpenSSL          19.0.0
pyparsing          2.4.7
pyperclip          1.8.1
pyrsistent         0.17.3
PySocks            1.7.0
python-dateutil    2.8.1
pytz               2020.4
PyYAML             5.3.1
requests           2.22.0
rfc3339-validator  0.1.2
rfc3986-validator  0.1.1
ruamel.yaml        0.16.12
ruamel.yaml.clib   0.2.2
setuptools         46.0.0
six                1.12.0
smmap              3.0.4
stevedore          3.2.2
strictyaml         1.0.6
torf               3.1.3
ulid-py            1.1.0
unfurl             0.0.1.dev391
urllib3            1.24.2
virtualenv         20.1.0
virtualenv-clone   0.5.4
wcwidth            0.2.5
webcolors          1.11.1
Werkzeug           1.0.1
wget               3.2
wheel              0.34.2
win-inet-pton      1.1.0
wincertstore       0.2
zipp               3.4.0

**Comment by TheresAFewConors** [comment]
@robmitch5 it took a bit of time but I was able to recreate the bug. 

It looks like its tied to the `unfurl` package required when you specify `python3` instead of just `python`, and appears to fail on install of the `ansible` package. It does seems to work correctly though if I don't specify `python3`, and instead just run `python Sooty.py`, which is interesting. 

Could you try that on your end as well?

**Comment by robmitch5** [comment]
@TheresAFewConors  
Below are the results. 

python Sooty.py
Traceback (most recent call last):
  File "Sooty.py", line 11, in <module>
    from unfurl import core
ImportError: No module named unfurl

**Comment by indigocarmen** [comment]
I hit this as well - initially was using Python 2.7.18. Switching the command to python3 (Python 3.8.6) fixed the issue.

**Comment by thelordharry** [comment]
I get this:

Sooty-master# python3 Sooty.py
Traceback (most recent call last):
  File "Sooty.py", line 11, in <module>
    from unfurl import core
ImportError: cannot import name 'core' from 'unfurl' (/usr/local/lib/python3.8/dist-packages/unfurl/__init__.py)

PIP3 LIST:

Sooty-master# pip3 list
Package                Version             
---------------------- --------------------
alabaster              0.7.8               
ansible                2.9.18              
appdirs                1.4.4               
apt-clone              0.2.1               
apturl                 0.5.2               
asn1crypto             0.24.0              
attrs                  20.3.0              
Babel                  2.6.0               
beautifulsoup4         4.8.2               
blinker                1.4                 
Brlapi                 0.7.0               
certifi                2019.6.16           
chardet                3.0.4               
click                  7.1.2               
click-log              0.3.2               
cliff                  3.7.0               
cmd2                   1.5.0               
colorama               0.4.3               
command-not-found      0.3                 
configobj              5.0.6               
cryptography           2.8                 
cupshelpers            1.0                 
dbus-python            1.2.16              
defer                  1.0.6               
distlib                0.3.1               
distro                 1.4.0               
docopt                 0.6.2               
docutils               0.16                
entrypoints            0.3                 
feedparser             5.2.1               
filelock               3.0.12              
gitdb                  4.0.5               
GitPython              3.1.14              
gitsome                0.8.0               
grpcio                 1.16.1              
httplib2               0.14.0              
idna                   2.8                 
ifaddr                 0.1.6               
imagesize              1.2.0               
IMDbPY                 6.8                 
Jinja2                 2.10.1              
jsonpointer            2.0                 
jsonschema             3.2.0               
keyring                18.0.1              
launchpadlib           1.10.13             
lazr.restfulclient     0.14.2              
lazr.uri               1.0.3               
louis                  3.12.0              
macaroonbakery         1.3.1               
Mako                   1.1.0               
MarkupSafe             1.1.0               
nemo-emblems           4.8.1               
netifaces              0.10.4              
nose                   1.3.7               
numpydoc               0.7.0               
oauthlib               3.1.0               
onboard                1.4.1               
packaging              20.3                
PAM                    0.4.2               
pbr                    5.5.1               
pexpect                4.6.0               
Pillow                 7.0.0               
pip                    20.0.2              
pipenv                 2020.11.15          
ply                    3.11                
prettytable            2.1.0               
prompt-toolkit         2.0.10              
protobuf               3.6.1               
psutil                 5.5.1               
pycairo                1.16.2              
pycparser              2.19                
pycrypto               2.6.1               
pycups                 1.9.73              
pycurl                 7.43.0.2            
Pygments               2.3.1               
PyGObject              3.36.0              
PyICU                  2.4.2               
pyinotify              0.9.6               
PyJWT                  1.7.1               
pymacaroons            0.13.0              
PyNaCl                 1.3.0               
pyparsing              2.4.6               
pyparted               3.11.2              
pyperclip              1.8.2               
pyRFC3339              1.1                 
pyrsistent             0.17.3              
python-apt             2.0.0+ubuntu0.20.4.4
python-dateutil        2.8.1               
python-debian          0.1.36ubuntu1       
python-xapp            2.0.2               
python-xlib            0.23                
pytz                   2019.3              
pyxattr                0.6.1               
pyxdg                  0.26                
PyYAML                 5.3.1               
reportlab              3.5.34              
requests               2.22.0              
requests-file          1.4.3               
requests-unixsocket    0.2.0               
rfc3339-validator      0.1.2               
rfc3986-validator      0.1.1               
roman                  2.0.0               
ruamel.yaml            0.16.13             
ruamel.yaml.clib       0.2.2               
SecretStorage          2.3.1               
setproctitle           1.1.10              
setuptools             45.2.0              
simplejson             3.16.0              
six                    1.14.0              
smmap                  3.0.5               
soupsieve              1.9.5               
Sphinx                 1.8.5               
stevedore              3.3.0               
systemd-python         234                 
tinycss2               1.0.2               
tldextract             2.2.1               
ubuntu-advantage-tools 20.3                
ubuntu-drivers-common  0.0.0               
ufw                    0.36                
unfurl                 0.2.2               
Unidecode              1.1.1               
urllib3                1.25.8              
virtualenv             20.4.2              
virtualenv-clone       0.5.4               
wadllib                1.3.3               
wcwidth                0.1.8               
webcolors              1.11.1              
webencodings           0.5.1               
wheel                  0.34.2              
xkit                   0.0.0               
xonsh                  0.9.13              
youtube-dl             2020.3.24           
zeroconf               0.24.4 

FWIW, I'm running:

  Operating System: Linux Mint 20.1
            Kernel: Linux 5.4.0-66-generic


I'd love to be able to run this properly as I'm sure I'd find it an incredibly useful addition to my SOC arsenal.

Any info gratefully received. Thank you!

**Comment by thelordharry** [comment]
Installed Python (2) and tried again:

Sooty-master# python Sooty.py
Traceback (most recent call last):
  File "Sooty.py", line 11, in <module>
    from unfurl import core
ImportError: No module named unfurl

So for me, 2 or 3 does not work.

**Comment by TheresAFewConors** [comment]
@thelordharry thanks for letting me know - looks like the unfurl package is causing issues on *nix systems when installing from the requirements.txt file, can you try manually installing the missing packages? If that doesn't work I'll add it as a bug and work on correcting it

**Comment by thelordharry** [comment]
I've been going through one-by-one and installing the missing packages by running the **python3 Sooty.py** command and then waiting for it to fail with the required missing module name. I'd correlate that to the requirements.txt and then (for example) type > **pip3 install dfir-unfurl==20200812**

However, I've gotten to the stage below:

Sooty-master# python3 Sooty.py
Traceback (most recent call last):
  File "Sooty.py", line 23, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'

So I figured it would be:

Couldn't see anything 'tkinter' in the requirements file so just tried:

pip3 install tkinter

which shows:

Sooty-master# pip3 install tkinter
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter

_____________________________

I'm sorry, I've hit the end of the road here as I'm a little out of my comfort zone as it is.

Happy to try any other suggestions.

Lastly, thank you for your time. I can't wait to try your software when we get it up and running.

**Comment by TheresAFewConors** [comment]
Thanks for going through them - just to confirm you have installed packages from the requirements.txt file too? 

'pip install -r requirements.txt'

The error you are getting now is related to a missing package on your system. Some corporate networks will block downloading python libraries for good reason, so make sure you're not being blocked too

**Comment by thelordharry** [comment]
I had previously installed from the requirements.txt with the:

pip3 install -r requirements.txt

command.

I ran it again. Below is the output (apologies in advance for its verbosity!):

Also, I am on my own wireless network and equipment with no restrictions. 

Sooty-master# sudo apt install python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
-----------
Sooty-master# sudo apt install python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.



Sooty-master# pip3 install -r requirements.txt
Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
Requirement already satisfied: asn1crypto==0.24.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 1)) (0.24.0)
Requirement already satisfied: certifi==2019.6.16 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (2019.6.16)
Collecting cffi==1.12.3
  Using cached cffi-1.12.3.tar.gz (456 kB)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (3.0.4)
Collecting cryptography==2.7
  Using cached cryptography-2.7-cp34-abi3-manylinux1_x86_64.whl (2.3 MB)
Requirement already satisfied: dfir-unfurl==20200812 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (20200812)
Collecting dnspython==1.16.0
  Using cached dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
Requirement already satisfied: idna==2.8 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 8)) (2.8)
Requirement already satisfied: ipwhois==1.1.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 9)) (1.1.0)
Requirement already satisfied: pycparser==2.19 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 10)) (2.19)
Collecting pyOpenSSL==19.0.0
  Using cached pyOpenSSL-19.0.0-py2.py3-none-any.whl (53 kB)
Collecting PySocks==1.7.0
  Using cached PySocks-1.7.0-py3-none-any.whl (16 kB)
Requirement already satisfied: requests==2.22.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 14)) (2.22.0)
Collecting six==1.12.0
  Using cached six-1.12.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: strictyaml==1.0.6 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 16)) (1.0.6)
Collecting urllib3==1.24.2
  Using cached urllib3-1.24.2-py2.py3-none-any.whl (131 kB)
Collecting win-inet-pton==1.1.0
  Using cached win_inet_pton-1.1.0-py2.py3-none-any.whl (4.8 kB)
Collecting wincertstore==0.2
  Using cached wincertstore-0.2-py2.py3-none-any.whl (8.8 kB)
Processing /root/.cache/pip/wheels/bd/a8/c3/3cf2c14a1837a4e04bd98631724e81f33f462d86a1d895fae0/wget-3.2-py3-none-any.whl
Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (from dfir-unfurl==20200812->-r requirements.txt (line 6)) (3.6.1)
Requirement already satisfied: flask in /usr/local/lib/python3.8/dist-packages (from dfir-unfurl==20200812->-r requirements.txt (line 6)) (1.1.2)
Requirement already satisfied: maclookup in /usr/local/lib/python3.8/dist-packages (from dfir-unfurl==20200812->-r requirements.txt (line 6)) (1.0.3)
Requirement already satisfied: pycountry in /usr/local/lib/python3.8/dist-packages (from dfir-unfurl==20200812->-r requirements.txt (line 6)) (20.7.3)
Requirement already satisfied: publicsuffix2 in /usr/local/lib/python3.8/dist-packages (from dfir-unfurl==20200812->-r requirements.txt (line 6)) (2.20191221)
Requirement already satisfied: torf in /usr/local/lib/python3.8/dist-packages (from dfir-unfurl==20200812->-r requirements.txt (line 6)) (3.1.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.8/dist-packages (from dfir-unfurl==20200812->-r requirements.txt (line 6)) (2.5)
Requirement already satisfied: ulid-py in /usr/local/lib/python3.8/dist-packages (from dfir-unfurl==20200812->-r requirements.txt (line 6)) (1.1.0)
Requirement already satisfied: flask-cors in /usr/local/lib/python3.8/dist-packages (from dfir-unfurl==20200812->-r requirements.txt (line 6)) (3.0.10)
Requirement already satisfied: ruamel.yaml>=0.14.2 in /usr/local/lib/python3.8/dist-packages (from strictyaml==1.0.6->-r requirements.txt (line 16)) (0.16.13)
Requirement already satisfied: python-dateutil>=2.6.0 in /usr/local/lib/python3.8/dist-packages (from strictyaml==1.0.6->-r requirements.txt (line 16)) (2.8.1)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/lib/python3/dist-packages (from flask->dfir-unfurl==20200812->-r requirements.txt (line 6)) (2.10.1)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.8/dist-packages (from flask->dfir-unfurl==20200812->-r requirements.txt (line 6)) (1.0.1)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.8/dist-packages (from flask->dfir-unfurl==20200812->-r requirements.txt (line 6)) (1.1.0)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.8/dist-packages (from flask->dfir-unfurl==20200812->-r requirements.txt (line 6)) (7.1.2)
Requirement already satisfied: future in /usr/local/lib/python3.8/dist-packages (from maclookup->dfir-unfurl==20200812->-r requirements.txt (line 6)) (0.18.2)
Requirement already satisfied: flatbencode==0.2.* in /usr/local/lib/python3.8/dist-packages (from torf->dfir-unfurl==20200812->-r requirements.txt (line 6)) (0.2.1)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.8/dist-packages (from networkx->dfir-unfurl==20200812->-r requirements.txt (line 6)) (4.4.2)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from ruamel.yaml>=0.14.2->strictyaml==1.0.6->-r requirements.txt (line 16)) (0.2.2)
Building wheels for collected packages: cffi
  Building wheel for cffi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9m5_dy7c/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9m5_dy7c/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-geyer8bc
       cwd: /tmp/pip-install-9m5_dy7c/cffi/
  Complete output (56 lines):
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/cffi
  copying cffi/recompiler.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/model.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/cparser.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/error.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/__init__.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/lock.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/commontypes.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/api.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/verifier.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/_embedding.h -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.8/cffi
  running build_ext
  building '_cffi_backend' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/c
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.8/c/_cffi_backend.o
  c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
     15 | #include <ffi.h>
        |          ^~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cffi
  Running setup.py clean for cffi
Failed to build cffi
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
Installing collected packages: cffi, six, cryptography, dnspython, pyOpenSSL, PySocks, urllib3, win-inet-pton, wincertstore, wget
    Running setup.py install for cffi ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9m5_dy7c/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9m5_dy7c/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zu7sys6r/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/cffi
         cwd: /tmp/pip-install-9m5_dy7c/cffi/
    Complete output (56 lines):
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/cffi
    copying cffi/recompiler.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/model.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/cparser.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/error.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/__init__.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/lock.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/commontypes.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/api.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/verifier.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/_embedding.h -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.8/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/c
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.8/c/_cffi_backend.o
    c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
       15 | #include <ffi.h>
          |          ^~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9m5_dy7c/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9m5_dy7c/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zu7sys6r/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/cffi Check the logs for full command output.

**Comment by thelordharry** [comment]
Apologies again as my lack of Python knowledge is not helping matters here, and I appreciate that's not your fault. 

But thank you for taking the time to read all this and take a look.

**Comment by thelordharry** [comment]
If it makes matter easier, I'm more than happy to try another distro. What are you using? Lol, if it works for you, I'll try the same setup and try and replicate it.

Linux blows my mind sometimes, and add on top of that the complexities of Python and (boom). Lol.

**Comment by TheresAFewConors** [comment]
I'll take a look through and see if I can identify the problem shortly. 

For using Sooty I tend to use Windows as it's on my work machine by default, and is pretty consistent. There's a few bugs that pop up in *nix that I need to fix

**Comment by thelordharry** [comment]
Thanks 😊

FWIW I've tried doing the same thing (brand new install) on my Win 10 laptop.

Short story:

After installing Python 3, cloning the Sooty software, and installing all the components of the 'requirements.txt' individually (and without a version number, i.e.: pip install ipwhois), I was then able to launch Sooty.py.

I do not yet understand Python, nor what it all means, but maybe this will be of some help to anyone else.

Please don't let me tell you your business, as you understand it infinitely more than me I'm sure, but should your requirements.txt just have the component name without version number> Unless the version number is needed for a specific purpose.

**Comment by thelordharry** [comment]
Further: The 'requirements.txt' populated with just the below seems to import without issue. The Sooty.py then launches successfully?

As I say, if you need a specific version number of something, this might mess everything up, but for now, it seems to be working for me!

asn1crypto
certifi
cffi
chardet
cryptography
dfir-unfurl
dnspython
idna
ipwhois
pycparser
pyOpenSSL
PySocks
pywin32
requests
six
strictyaml
urllib3
win-inet-pton
wincertstore
wget

**Comment by TheresAFewConors** [comment]
Glad to hear you got it working. This is mainly tested on Win10 currently so it is easier to get it running. 

As for the requirements.txt files you don't *have* to have the specific version defined, but it is usually best practice to avoid issues down the line. The pip docs do a pretty good job of explaining this, [link here](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format)
