### ISSUE TITLE
Visual Studio 2015 dependency

### ISSUE THREAD

**Issue by mzje** [TheresAFewConors/Sooty#75]
Apologies if this is a daft question but to get the email analysis working I had to install VS 2015 Update 3 however I note that mainstream support has now ended. (https://support.microsoft.com/en-gb/lifecycle/search/1117) 

Is there a more recent version this works with/is there a plan to move to something newer?

**Comment by TheresAFewConors** [comment]
hi @mzje 

I run python from the cmd line / develop in Pycharm so I don't tend to see issues that come up from VS. If you install python system wide and run from cmd.exe it should function correctly. 

I may in future look into providing support for VS, but currently that is not supported.
