### ISSUE TITLE
Virustotal error

### ISSUE THREAD

**Issue by xxCoffeexx** [TheresAFewConors/Sooty#77]
Pip install the requirement.txt in Kali linux.

 ---------------------------------
 R E P U T A T I O N     C H E C K
 ---------------------------------
Enter IP, URL or Email Address: 8.8.8.8

 WHO IS REPORT:
  CIDR:      8.0.0.0/9
  Name:      LVLT-ORG-8-8
  Range:     8.0.0.0 - 8.127.255.255
  Descr:     Level 3 Parent, LLC
  Country:   US
  State:     LA
  City:      Monroe
  Address:   100 CenturyLink Drive
  Post Code: 71203
  Created:   1992-12-01
  Updated:   2018-04-23

 VirusTotal Report:
Traceback (most recent call last):
  File "Sooty.py", line 1218, in <module>
    mainMenu()
  File "Sooty.py", line 180, in mainMenu
    switchMenu(input())
  File "Sooty.py", line 55, in switchMenu
    repChecker()
  File "Sooty.py", line 392, in repChecker
    params = {'apikey': configvars.data['VT_API_KEY'], 'ip': wIP}
NameError: name 'configvars' is not defined

Any idea?

**Comment by sarthak9426** [comment]
@xxCoffeexx Did you rename the example_config.yaml to config.yaml as written in the Readme before running the program?

**Comment by TheresAFewConors** [comment]
@xxCoffeexx looks like its related to the API key for VT - its free to set up, just make sure you rename the file from `example_config.yaml` to `config.yaml`
