### ISSUE TITLE
Unable to use the tool when use ubuntu with proxy setting

### ISSUE THREAD

**Issue by adrianckc** [TheresAFewConors/Sooty#78]
**What is the Issue you are experiencing?**
Give a description of what issue you are facing? eg. issue installing from requirements file, etc.
Cannot use the sooty.py when i use the ubuntu PC with proxy setting

**What Operating System are you using?**
The OS of the device that Sooty is running on.
ubuntu 20

**Additional Information**
Any additional information that may benefit this case.

**Comment by TheresAFewConors** [comment]
Can you show me the error you are receiving? It's likely related to a certificate issue which can be toggled off system wide.

**Comment by TheresAFewConors** [comment]
just giving this a bump - if no response ill close this out

**Comment by TheresAFewConors** [comment]
closing due to no updates on issue
