### ISSUE TITLE
Add Phish Tank Capability

### ISSUE THREAD

**Issue by euanbirch** [TheresAFewConors/Sooty#8]
#7 https://www.phishtank.com/api_info.php - Verify if a URL has been used in a phishing attack

**Comment by euanbirch** [comment]
#7 https://github.com/AlienVault-OTX/ApiV2 - Add Threat Crowd functionality

**Comment by TheresAFewConors** [comment]
- I will take a look into PhishTank - I'm currently working on a phishing specific module for the 1.2 release so it could be a great addition to the module.

- AlienVault is already in the works for the rep checker - the more checks that are done against reliable sites the better the info imo.

tldr;
PhishTank - Most Likely
AlientVault - Definitely

Thanks for the submission - I'll keep this ticket open as a reminder and close it when they've been added. It might be a week or two though just so you're aware

**Comment by Gurulhu** [comment]
@TheresAFewConors if you don't mind, I kinda got too entertained and added PhishTank verification to my fork. 
I could PR this one.

**Comment by TheresAFewConors** [comment]
@Gurulhu yeah if you want to open a PR that'd be extremely helpful - I'll review it this afternoon and we can try get it merged

**Comment by Gurulhu** [comment]
> @Gurulhu yeah if you want to open a PR that'd be extremely helpful - I'll review it this afternoon and we can try get it merged

Sorry, I wasn't able to PR sooner. Up to review already.

**Comment by TheresAFewConors** [comment]
No worries at all. There's no rush. Just reviewed and left a comment.

**Comment by TheresAFewConors** [comment]
Closed due to inactivity
