### ISSUE TITLE
module not found error 

### ISSUE THREAD

**Issue by johnsilverkim** [TheresAFewConors/Sooty#88]
I got an error when running the command  " Python sooty.py"

Error message - File line 12 from unfurl import core
ModulenotFounderror :No module name 'unfurl'

**Comment by jenetiks** [comment]
You need to install the requirements first. Try the following:

`python3 -m pip install -r requirements.txt`

Should install missing libraries you need to run the app itself.

**Comment by TheresAFewConors** [comment]
user issue
