### ISSUE TITLE
UnboundLocalError: local variable 'f' referenced before assignment

### ISSUE THREAD

**Issue by neilunderwood** [TheresAFewConors/Sooty#96]
**Describe the bug**
I am getting failures on random modules.  The common denominator seems to be "UnboundLocalError: local variable 'f' referenced before assignment".  My example in the screenshot is failing at BadIP's, but other modules fail in this way as well.

**Reproduction Steps**
1. launch sooty
2. choose menu option 3
3. enter email address
...

**Expected behavior**
A clear and concise description of what was expected to happen.
Expect to see valid results returned when checking email reputation

**Screenshots**
![image](https://user-images.githubusercontent.com/619619/161566333-c6d473d7-869d-4a06-ab2e-90d5ef03eeb9.png)

**Desktop Operating System:**
 - OS: [e.g. Win10, Linux, etc.]
Debian 10 (WSL 1)

**Additional context**

**Comment by BartoszJelen** [comment]
I am facing the same problem. In the code, it looks like for def checker,
 try:
        TOR_URL = "https://check.torproject.org/cgi-bin/TorBulkExitList.py?ip=1.1.1.1"
        req = requests.get(TOR_URL)
        print("\n TOR Exit Node Report: ")
        f.write("\n\n --------------------------------- ")
        f.write("\n TOR Exit Node Report: ")
        f.write("\n --------------------------------- \n")
        
        f variable is not assign to anything

**Comment by jrmain** [comment]
I get this same error when I run the reputation checker on an email address. Ubuntu 18. Most of the other functions work, and the reputation check otherwise works on email addresses, but it would be nice to fix this. Can you provide a bit more information about the possible cause being a certificate issue and restricted networks?

**Comment by TheresAFewConors** [comment]
> I get this same error when I run the reputation checker on an email address. Ubuntu 18. Most of the other functions work, and the reputation check otherwise works on email addresses, but it would be nice to fix this. Can you provide a bit more information about the possible cause being a certificate issue and restricted networks?

It is to do with the application not having a signed certificate when making outbound calls. It can be disabled, however is often easy to test by dropping off the network and seeing the issue persists. If it goes away; its the cert. If it stays then its something else that needs to look into.

**Comment by jrmain** [comment]
Sorry to be a pest, but can you provide any hints as to how I would go about fixing the cert problem? Alternatively, how I can disable whatever is causing the problem, as you've suggested is possible?
